# Generated by Django 5.0.4 on 2024-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0002_rename_mymodel_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
