# Generated by Django 5.0.4 on 2024-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0003_remove_login_name_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='FirstName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='LastName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
