# Generated by Django 5.0.4 on 2024-05-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0004_login_firstname_login_lastname_login_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Register',
        ),
    ]
