# Generated by Django 5.0.4 on 2024-05-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0005_rename_login_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['FirstName'], 'verbose_name': 'Register'},
        ),
        migrations.AlterField(
            model_name='register',
            name='FirstName',
            field=models.CharField(default='Ahmed', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='LastName',
            field=models.CharField(default='Nazeer', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='ahmed.m.nazeer.18@gmail.com', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='123', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(default='01556162788', max_length=11, verbose_name='Phone'),
        ),
    ]
