# Generated by Django 5.0.4 on 2025-04-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0006_alter_register_options_alter_register_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchByStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=255)),
                ('eNum', models.IntegerField()),
                ('mNum', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Search By Stations',
                'ordering': ['stationName'],
            },
        ),
    ]
