# Generated by Django 5.0.4 on 2025-04-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0007_searchbystations'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=14)),
                ('bike_type', models.CharField(choices=[('manual', 'Manual'), ('electrical', 'Electrical')], max_length=50)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_station', to='agalty.searchbystations')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_station', to='agalty.searchbystations')),
            ],
            options={
                'verbose_name': 'Start Ride',
                'verbose_name_plural': 'Start Rides',
                'ordering': ['-start_date'],
            },
        ),
    ]
