# Generated by Django 5.0.4 on 2025-04-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0008_startride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startride',
            options={'ordering': ['-full_name'], 'verbose_name': 'Start Ride', 'verbose_name_plural': 'Start Rides'},
        ),
        migrations.RemoveField(
            model_name='startride',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='startride',
            name='start_time',
        ),
    ]
