# Generated by Django 5.0.4 on 2025-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0009_alter_startride_options_remove_startride_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=14)),
                ('trip_number', models.IntegerField()),
                ('bike_type', models.CharField(max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
