# Generated by Django 5.0.4 on 2025-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0010_checkoutride'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutride',
            name='payment_type',
            field=models.CharField(default='Not selected', max_length=100),
        ),
    ]
