# Generated by Django 5.0.4 on 2025-04-29 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0011_checkoutride_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='startride',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
