# Generated by Django 5.0.4 on 2025-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agalty', '0012_startride_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='startride',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
